### ISSUE TITLE
Windows Playback / Chromecast Issues

### ISSUE THREAD

**Issue by zQueal** [mafintosh/playback#126]
Using [this build](https://github.com/mafintosh/playback/issues/63#issuecomment-185533196) I was unable to get any MKV video to play--although sound worked fine. MP4 video and audio works fine. Chromecast option doesn't work _at all_.

Just throwing this ticket up to make the issues known.

**Comment by electricduck** [comment]
It explicitly states in the README that only `mp4` and `webm` are supported
