### ISSUE TITLE
npm start can't work

### ISSUE THREAD

**Issue by itlwy** [mafintosh/playback#130]
No app popup after running npm start.
as below:
E:\project\playback-master>npm run start

> playback@1.6.0 start E:\project\playback-master
> electron app.js

nothing happen

**Comment by geenloop** [comment]
same here, but on MAC 10.14.5 (Mojave)... install DEP and update all but still getting this error:

[https://github.com/Homebrew/homebrew-core/issues/2869](https://github.com/Homebrew/homebrew-core/issues/2869)

nothing helped, still googling...

ERROR:


/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run start --scripts-prepend-node-path=auto

> playback@1.6.0 start /Users/admin/WebstormProjects/playback
> electron app.js

[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
2019-08-28 16:56:45.796 Electron[21310:5808023] *** WARNING: Textured window <AtomNSWindow: 0x7fd327474dc0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

Process finished with exit code 0
