### ISSUE TITLE
Add to Homebrew-Cask

### ISSUE THREAD

**Issue by vinkla** [mafintosh/playback#16]
Pull request opened at https://github.com/caskroom/homebrew-cask/pull/10572

**Comment by maxogden** [comment]
@vinkla I am not familiar with homebrew-cask. What maintenance is required to keep versions there in sync with the latest release here?

**Comment by vinkla** [comment]
Nothing really. You only have to push a new version number with a new sha256 key.

```ruby
cask :v1 => 'playback' do
  version '1.1.0'
  sha256 'a9849a894e07e0b4f0c60095275752848117fb1d8e5de7781737bc03553fc708'

  url "https://github.com/mafintosh/playback/releases/download/v#{version}/Playback.app.zip"
  name 'Playback'
  homepage 'https://github.com/mafintosh/playback'
  license :oss

  app 'Playback.app'
end
```

If you guys later on have a defined URL for the latest version its possible to just write the following:

```ruby
version :latest
sha256 :no_check
```

When this has been added it usually has no maintenance require what so ever.

**Comment by vinkla** [comment]
Merged.
