### ISSUE TITLE
graphical ui

### ISSUE THREAD

**Issue by mafintosh** [mafintosh/playback#2]
playback is a minimalistic video player build on top of atom-shell. it supports playing normal video files, video files shared using bittorrent, (and in the future, videos from youtube). it also has support for broadcasting what you're currently watching over the local network so that multiple people can watch the same video at the same time.

basic functionality is pretty much done but it needs a graphical ui. i'm thinking it should be as minimal as possible (think quicktime on osx) where there isn't any ui until you mouse over the player.

components wise we probably need

* top menubar with the osx close/minimize buttons and buttons for broadcasting what you are watching or subscribing to what someone else on the same network is watching
* a playlist that shows what is currently queued
* an info panel that shows how fast you are downloading if the thing you are watching is a torrent and how many peers you are connected to
* controls (play/pause, a timeline that shows how far you've watched, and a timer)

any help with the design aspect of this would be greatly appreciated :) am happy to implement from mockups, or whatever else works. leave ideas in the thread below

**Comment by maxogden** [comment]
for minimalism the best peeps in the game are @jxnblk and @mrmrs, maybe http://jxnblk.com/skull/ would be useful here

**Comment by jemory** [comment]
I have some questions about the expected functionality of the top menubar.

- What should happen when the broadcast button is pressed?
- What should happen when the button for selecting broadcasts is pressed? Would there be a list? Modal?
- Is the app aware of whether or not broadcasts are available? I.e., should the select button be permanent, or only visible when a broadcast it available?

One other question I have: what is the primary method of selecting a video for playback in the first place and how are videos added to the queue? File menu? Magnet Links? Drag and drop? All of the above? Something else?

Sounds like a cool app!

**Comment by freeall** [comment]
@jemory videos should probably be added through magnet links and drag and drop. I'm looking into getting the magnet links to work.

**Comment by mafintosh** [comment]
> What should happen when the broadcast button is pressed? Any dialog involved?

No dialog is needed (the app just starts broadcasting to other people on the network that you are available for broadcast). The broadcast button could change state to show that you are broadcasting now.

> What should happen when the button for selecting broadcasts is pressed? Would there be a list? Modal?

The way it works now is that when subscribing it just starts showing the first broadcast it finds on the network. I think we can continue with this behaviour for a while and worry about having modal later incase more than one is found.

> Is the app aware of whether or not broadcasts are available? I.e., should the select button be permanent, or only visible when a broadcast is available?

Yes the app is aware so we could "gray" out the button if no broadcast is available

>  what is the primary method of selecting a video for playback in the first place and how are videos added to the queue? File menu? Magnet Links? Drag and drop? All of the above? Something else?

I'm thinking all of the above :)

**Comment by mafintosh** [comment]
@freeall nice! make a "registerProtocol" module :)

**Comment by freeall** [comment]
@mafintosh my thoughts exactly (about the module) :)

**Comment by mafintosh** [comment]
@freeall i made a separate issue for the protocol handler stuff in #3

**Comment by bmathews** [comment]
Here's somethin quick I threw together:

![image](https://cloud.githubusercontent.com/assets/848347/6989962/7cf0b62c-da17-11e4-9d0b-64761db7922b.png)

![image](https://cloud.githubusercontent.com/assets/848347/6989975/ac79fa70-da17-11e4-89ef-8cb2c1231b32.png)

If you like the direction, I could finish it up.

**Comment by mafintosh** [comment]
@jemory looks great! please finish it up :) i'm thinking we need a subscribe button as well? maybe that should just be located the same place add the "add file" buttons

**Comment by mafintosh** [comment]
I meant to mention @bmathews above

**Comment by bmathews** [comment]
Sure thing. For the list of available broadcasts, what kind of information will be available to us to show? Filename? IP? Computer name?

**Comment by mafintosh** [comment]
@bmathews all of the above :)

**Comment by bmathews** [comment]
Here are some quick ideas for broadcasting/subscribing and playing/streaming. Colors/states/alignment of things are real rough in these mockups. 

¯\\\_(ツ)_/¯

![image](https://cloud.githubusercontent.com/assets/848347/6990753/b29842ac-da28-11e4-82b0-83e8c4758df4.png)

![image](https://cloud.githubusercontent.com/assets/848347/6990757/dc82c970-da28-11e4-869d-908a2258e54b.png)

![image](https://cloud.githubusercontent.com/assets/848347/6990779/3b51e882-da29-11e4-90c9-9cf84078cf92.png)

![image](https://cloud.githubusercontent.com/assets/848347/6990798/d2a967a0-da29-11e4-9e4e-eba56a398980.png)

**Comment by bmathews** [comment]
Feel free to ignore any of these ideas or implement it differently. But maybe this helps or gives you some ideas/foundation to build on?

**Comment by mafintosh** [comment]
@bmathews thanks so much for making these. i'm gonna try to implement that now. btw which font are you using?

**Comment by bmathews** [comment]
Roboto. Can get here. Probably just need regular/medium/bold.
http://www.google.com/fonts#UsePlace:use/Collection:Roboto

**Comment by bmathews** [comment]
Or I could add it later if you just want to use helvetica for now.

**Comment by daviferreira** [comment]
@bmathews nice work, beautiful stuff :+1:

**Comment by mafintosh** [comment]
@bmathews most of the ui is implemented now in master. i'm wondering what app should show when the playlist is empty (right now its just a black screen). any ideas?

**Comment by bmathews** [comment]
@mafintosh The cat's pretty good, but I'll keep thinking of some ideas.

**Comment by freeall** [comment]
I think the cat is good, but maybe it should have a few seconds of waiting after each wag

**Comment by maxogden** [comment]
the idea behind the cat is that it will cause massive viral success of the app

**Comment by freeall** [comment]
@maxogden a cat virus if I'm not mistaken? A catirus

**Comment by maxogden** [comment]
closing in favor of smaller, more focused issues
