### ISSUE TITLE
magnet link protocol handler

### ISSUE THREAD

**Issue by mafintosh** [mafintosh/playback#3]
would be cool if playback could register it self as a `magnet:` protocol handler so it would autoplay magnet links when you press them

**Comment by freeall** [comment]
The status right now is that I use https://github.com/maxogden/atom-shell-packager to create an .app. In that .app there is a `Info.plist` file which I change an add this:

```
<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleURLName</key>
        <string>BitTorrent Magnet URL</string>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>magnet</string>
        </array>
    </dict>
</array>
```

With that in place Chrome (and other applications) will now open `magnet:` links in Playback. However, I'm still looking into how to read the passed value.

**Comment by mafintosh** [comment]
this should work in master now

**Comment by mafintosh** [comment]
do `npm run bundle` to get a Playback.app build that has the protocol handlers set
