### ISSUE TITLE
Controls break when title is too long (or window to narrow)

### ISSUE THREAD

**Issue by mikker** [mafintosh/playback#30]
eg. ![](http://s3.brnbw.com/Screen-Shot-2015-04-23-08-58-54.png)

Suggested solution: Titles get truncated with a `&hellip;`
This is the stuff flexbox is made for. I could give it a try if you'd like me to?

**Comment by freeall** [comment]
@mikker sounds good. It'd be great if you could give it a go.

**Comment by LinusU** [comment]
`text-overflow: ellipsis;`

https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

**Comment by mikker** [comment]
@LinusU Sure, but those need a `width` on the container element. So floats wont work well.

**Comment by LinusU** [comment]
Absolutely, flexbox is awesome for that! I just wanted to give you a quick reference incase you didn't know about `text-overflow` :)

**Comment by mikker** [comment]
:+1: :new_moon_with_face:
