### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by mafintosh** [mafintosh/playback#4]
we need a custom icon for the .app file

**Comment by freeall** [comment]
Definitely

**Comment by bmathews** [comment]
On it

**Comment by xiplias** [comment]
Here is one you can use. Its from my old mixplayer project which I do not work on anymore.

![icon](https://cloud.githubusercontent.com/assets/8337/7009014/30a24586-dc8f-11e4-8092-7c1a34dc530e.png)

**Comment by bmathews** [comment]
A little generic, but does this work for now?

![image](https://cloud.githubusercontent.com/assets/848347/7011028/8e2637c4-dc5a-11e4-861d-adc93aa22f2b.png)

I've got the .icns ready with:
```
icon_128x128.png
icon_128x128@2x.png
icon_16x16.png
icon_16x16@2x.png
icon_256x256.png
icon_256x256@2x.png
icon_32x32.png
icon_32x32@2x.png
icon_512x512.png
icon_512x512@2x.png
```

**Comment by mafintosh** [comment]
@bmathews looks great! could you commit the files into a new icons folder? i've made you a owner on this repo as well so you should have access

**Comment by mafintosh** [comment]
nevermind - just saw your pr :)
