### ISSUE TITLE
Volume?

### ISSUE THREAD

**Issue by nicknikolov** [mafintosh/playback#45]
Hey, really cool app, thanks! Is there a plan to put in volume control? Or maybe I don't see it?
It could potentially replace my VLC for listening to music, too - it's so much prettier :)
I would just miss flac support.

Cheers

**Comment by deliciousfudge** [comment]
+1

**Comment by LestaD** [comment]
+1

**Comment by daisuke-nomura** [comment]
Volume control was already added.
Go release new version @mafintosh

**Comment by mafintosh** [comment]
done! https://github.com/mafintosh/playback/releases. sorry for the delay.

**Comment by feross** [comment]
:+1: :+1: :+1:
