### ISSUE TITLE
Ability to watch youtube and vimeo URLs by pasting their page URLs

### ISSUE THREAD

**Issue by balupton** [mafintosh/playback#92]
Would be nice to be able to pass something like https://youtu.be/cJ6PpX6xg-E?t=598 and have playback show the youtube media player inside it, or whatever is needed to play it.

Benefit for me would be able to watch a youtube video in a smaller resizeable video player, rather than in a web browser of which I am probably doing other things.

**Comment by bmathews** [comment]
@balupton You should be able to paste the non-shortened youtube url into playback. Try that? https://www.youtube.com/watch?v=cJ6PpX6xg-E

**Comment by balupton** [comment]
@bmathews yep it worked, I'll send a PR, one moment
